//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17379
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jcl.Navigate.Services.Contracts.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Jcl.Navigate.Services.Contracts.Tests.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;ArrayOfLineStatus xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns=&quot;http://webservices.lul.co.uk/&quot;&gt;
        ///&lt;LineStatus ID=&quot;0&quot; StatusDetails=&quot;&quot;&gt;
        ///&lt;BranchDisruptions/&gt;
        ///&lt;Line ID=&quot;1&quot; Name=&quot;Bakerloo&quot;/&gt;
        ///&lt;Status ID=&quot;GS&quot; CssClass=&quot;GoodService&quot; Description=&quot;Good Service&quot; IsActive=&quot;true&quot;&gt;
        ///&lt;StatusType ID=&quot;1&quot; Description=&quot;Line&quot;/&gt;
        ///&lt;/Status&gt;
        ///&lt;/LineStatus&gt;
        ///&lt;LineStatus ID=&quot;1&quot; StatusDetails=&quot;&quot;&gt;
        ///&lt;BranchDisruptions/&gt;
        ///&lt;Line ID=&quot;2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestLineStateXmlResponse {
            get {
                return ResourceManager.GetString("TestLineStateXmlResponse", resourceCulture);
            }
        }
    }
}
